language: php
script:
  - |
    tar -cvz \
      --exclude=bin \
      --exclude=tests \
      --exclude=editorconfig \
      --exclude=.gitignore \
      --exclude=.travis.yml \
      --exclude=changelog.log \
      --exclude=CHANGELOG.md \
      --exclude=phpunit.xml.dist \
      --exclude=README.md \
      --exclude=readme.txt \
      -f vxxx.tgz *
